name: Latest blog posts

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://keriko-blog.pages.dev/rss.xml"
          max_post_count: 5
          comment_tag_name: BLOG-POST-LIST
          template: "$newline- [$title]($url) · $date"